name: Validate-XML

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: korelstar/xmllint-problem-matcher@v1
      - name: Setup XMLLint
        run: sudo apt install --no-install-recommends -y libxml2-utils
      - name: Validate ModLinks.xml
        run: xmllint --noblanks ModLinks.xml --schema Schemas/ModLinks.xml
      - name: Validate APILinks
        run: xmllint --noblanks ApiLinks.xml --schema Schemas/ApiLinks.xml
